### ISSUE TITLE
Recipe publication date display

### ISSUE THREAD

**Issue by sebferrer** [curry-chronicles/curry-chronicles.github.io#31]
Sur la page d'une recipe, il va falloir prendre en compte le fait que l'on va récupérer une date au format d'une vraie date MongoDB afin de l'afficher comme on le fait maintenant, au lieu d'un simple string.

**Comment by bastienguillon** [comment]
Corrigé par https://github.com/curry-chronicles/curry-chronicles.github.io/commit/2c16fa65f2822dd721a3c66776bbdbaf869ae0b0
